version: '3.7'
services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - '3306:3306'
    volumes:
      - ./mysql8/data:/var/lib/mysql
      - ./mysql8/conf:/etc/mysql/conf.d
      - ./mysql8/logs:/logs
    command: --default-authentication-plugin=mysql_native_password