// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package books

import (
	"database/sql"
)

type Author struct {
	ID   int64
	Name string
	Bio  sql.NullString
}

type Book struct {
	ID          int64
	Title       string
	AuthorID    int64
	Description sql.NullString
}
